# Generated by Django 3.0.1 on 2019-12-31 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191231_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_modified',
        ),
    ]
